### ISSUE TITLE
Add details

### ISSUE THREAD

**Issue by lesteroyal** [flutterph/devs#111]
I'm Lester from manila ph. My hobby is to explore different kinds of the platform in software development. I hope I learn more with this community and meet a lot of friends.

**Comment by Jansalvador1445** [comment]
Hi @lesteroyal ! Just a quick question, Did your PR already Merge? is this a duplicated issue? if Yes kindly close the ticket. Thank you! :D

**Comment by lesteroyal** [comment]
I think sir my PR yesterday is not yet merged. I create a new one sir.

**Comment by Jansalvador1445** [comment]
I see, I think I added comments for that. I closed for both, please re-open which is the final or you can create a new PR.

**Comment by Jansalvador1445** [comment]
Closing this ticket.
