### ISSUE TITLE
Add Lidaniel Cinco to Dev Board

### ISSUE THREAD

**Issue by lidaniel5** [flutterph/devs#116]
Please Add my name in Dev board. Thanks

**Comment by Jansalvador1445** [comment]
Hi @lidaniel5 , You should add your name to the `dev.json`. make sure that there's no conflict. Thanks! 

After that, if all goods, we could merge it and add you as a contributor. Thanks!

**Comment by lidaniel5** [comment]
Ok noted. thanks

**Comment by Jansalvador1445** [comment]
Closing this issue
