### ISSUE TITLE
[design] Text Alignment for Roles

### ISSUE THREAD

**Issue by Celesica** [flutterph/devs#235]
For the roles, suggesting to use textAlign center for cohesion. It looks like it gets flushed left once role extends to the next line. The "about" section acts similarly but I guess it looks fine.

**Comment by Jansalvador1445** [comment]
Hi @Celesica ! Thank you for filling this ticket! This will improve our project UI! :D

**Comment by Jansalvador1445** [comment]
Closing this issue.
