### ISSUE TITLE
[feature] Add `image_url` to `Dev` model

### ISSUE THREAD

**Issue by joshuadeguzman** [flutterph/devs#9]

**Comment by ram231** [comment]
I just want to test out this feature. the draw back is to not push their `pubspec.yaml` file. bale gagamitin lang yung [github raw user content](https://raw.githubusercontent.com/) to load images on the network instead of assets. So that we can dynamically load these images.

```dart
class DevImage extends StatelessWidget {
  const DevImage(this.imageSource);
  final String imageSource;
  
  @override
  Widget build(BuildContext context) {
    if (kDebugMode) {
      return Image.asset(imageSource);
    }
    return Image.network("https://raw.githubusercontent.com/flutterph/devs/master/${imageSource}");
  }
}
```
What do you think @joshuadeguzman?

**Comment by joshuadeguzman** [comment]
Hi @ram231 ,

Thanks for looking into this. 

I think we can also simplify this, we can ask for the Github `username` instead.

```
https://avatars.githubusercontent.com/<username>
```

For example

```
https://avatars.githubusercontent.com/joshuadeguzman
```

Before working on this, the links for social handles #19 should be landed first.

At least with this one we will not "host" the assets for these.

What are your thoughts?

**Comment by ram231** [comment]
I think that's good. the file name should be their username so that there won't be overwritten files when they PR.
Example Code:
```dart
class DevImage extends StatelessWidget {
  const DevImage(this.imageSource);
  final String imageSource; // assets/dev/profile/ram231.png
  final String username;  // ram231
  @override
  Widget build(BuildContext context) {
    if (kDebugMode) {
      return Image.asset(imageSource);
    }
    return Image.network("https://raw.githubusercontent.com/$username/devs/master/${imageSource}");
  }
}
```
Above code is just a concept. Although it works like that as long as we have a fallback image(placeholder) if the forked repo was archived/deleted.

**Comment by Jansalvador1445** [comment]
This is merged
